/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe.
         *
         *     Unauthenticated and dependency-free. Cloud Run readiness probes hit
         *     this endpoint anonymously; dependency-aware readiness belongs to a
         *     future ``/ready`` added by the first task that introduces a
         *     dependency (T04 Vertex, T05 Postgres).
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/position-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Position Templates */
        get: operations["list_position_templates_position_templates_get"];
        put?: never;
        /** Create Position Template */
        post: operations["create_position_template_position_templates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/position-templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Position Template */
        get: operations["get_position_template_position_templates__template_id__get"];
        put?: never;
        post?: never;
        /** Archive Position Template */
        delete: operations["archive_position_template_position_templates__template_id__delete"];
        options?: never;
        head?: never;
        /** Update Position Template */
        patch: operations["update_position_template_position_templates__template_id__patch"];
        trace?: never;
    };
    "/rubric/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Active Rubric */
        get: operations["read_active_rubric_rubric_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CompetencySelection
         * @description One selected competency and whether it is mandatory.
         */
        CompetencySelection: {
            /**
             * Competency Id
             * Format: uuid
             */
            competency_id: string;
            /** Must Have */
            must_have: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Response body for ``GET /health`` — stable across revisions.
         */
        HealthResponse: {
            /**
             * Service
             * @constant
             */
            service: "techscreen-backend";
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /**
         * PositionLevel
         * @description Target seniority of a role — distinct from rubric per-competency levels.
         * @enum {string}
         */
        PositionLevel: "Junior" | "Middle" | "Senior" | "Tech Leader";
        /**
         * PositionTemplateCreate
         * @description Request body for creating a Position Template (the T13 POST shape).
         */
        PositionTemplateCreate: {
            /** Competency Ids */
            competency_ids: string[];
            /** Jd Text */
            jd_text?: string | null;
            level: components["schemas"]["PositionLevel"];
            /** Must Have Competency Ids */
            must_have_competency_ids?: string[];
            /** Stack Ids */
            stack_ids: string[];
            /** Title */
            title: string;
        };
        /**
         * PositionTemplateRead
         * @description Response body for reading a Position Template (the T13 GET shape).
         */
        PositionTemplateRead: {
            /** Archived At */
            archived_at: string | null;
            /** Competencies */
            competencies: components["schemas"]["CompetencySelection"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Jd Text */
            jd_text: string | null;
            level: components["schemas"]["PositionLevel"];
            /** Stack Ids */
            stack_ids: string[];
            /** Title */
            title: string;
        };
        /**
         * PositionTemplateUpdate
         * @description Partial-update body for a Position Template (the T13 PATCH shape).
         *
         *     All fields optional; only fields present in the request are applied (the
         *     service inspects ``model_fields_set``). Provided selection lists replace the
         *     set wholesale. The must-have ⊆ selected rule is checked here when both lists
         *     are present; the must-have-without-competency_ids case is rejected at the
         *     service layer (it needs the existing selected set to validate against).
         */
        PositionTemplateUpdate: {
            /** Competency Ids */
            competency_ids?: string[] | null;
            /** Jd Text */
            jd_text?: string | null;
            level?: components["schemas"]["PositionLevel"] | null;
            /** Must Have Competency Ids */
            must_have_competency_ids?: string[] | null;
            /** Stack Ids */
            stack_ids?: string[] | null;
            /** Title */
            title?: string | null;
        };
        /**
         * RubricSnapshot
         * @description The whole frozen tree for one rubric version.
         */
        RubricSnapshot: {
            /** Label */
            label: string;
            /**
             * Rubric Tree Version Id
             * Format: uuid
             */
            rubric_tree_version_id: string;
            /** Stacks */
            stacks: components["schemas"]["SnapshotStack"][];
        };
        /** SnapshotCompetency */
        SnapshotCompetency: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Levels */
            levels: components["schemas"]["SnapshotLevel"][];
            /** Name */
            name: string;
            /** Topics */
            topics: components["schemas"]["SnapshotTopic"][];
        };
        /** SnapshotCompetencyBlock */
        SnapshotCompetencyBlock: {
            /** Competencies */
            competencies: components["schemas"]["SnapshotCompetency"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Position */
            position: number;
        };
        /** SnapshotLevel */
        SnapshotLevel: {
            /** Descriptor */
            descriptor: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Rank */
            rank: number;
        };
        /** SnapshotStack */
        SnapshotStack: {
            /** Competency Blocks */
            competency_blocks: components["schemas"]["SnapshotCompetencyBlock"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** SnapshotTopic */
        SnapshotTopic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_position_templates_position_templates_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionTemplateRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_position_template_position_templates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PositionTemplateCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionTemplateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_position_template_position_templates__template_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionTemplateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_position_template_position_templates__template_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionTemplateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_position_template_position_templates__template_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PositionTemplateUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionTemplateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_active_rubric_rubric_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RubricSnapshot"];
                };
            };
        };
    };
}
