// generate-tokens.ts
//
// Reads docs/design/tokens/*.md (the canonical source of truth) and produces
// two committed artefacts deterministically:
//
//   1. app/frontend/src/design/tokens.ts        — typed `as const` token tree
//      consumed by tailwind.config.ts via theme.{spacing|extend.*}.
//   2. app/frontend/src/app/globals.css TOKENS  — CSS custom properties under
//      :root, in two layers (semantic-role layer + shadcn-alias layer).
//
// Same input bytes produce the same output bytes. The drift test
// (tokens.test.ts) and the pre-commit `tokens-drift` hook compare the
// regenerated bytes against the committed files.
//
// Run via:
//   pnpm tokens:generate    (writes both artefacts)
//   pnpm tokens:check       (--check; exits 1 with diff head on drift)

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

// -----------------------------------------------------------------------------
// Constants (paths + canonical role-to-shadcn alias mapping)
// -----------------------------------------------------------------------------

// Use renamed locals to avoid clashing with CommonJS `__dirname` / `__filename`
// when Jest transpiles ESM to CJS for the drift test (tokens.test.ts).
const SCRIPT_FILE = fileURLToPath(import.meta.url);
const SCRIPT_DIR = dirname(SCRIPT_FILE);

const REPO_ROOT = resolve(SCRIPT_DIR, "..", "..", "..");
const TOKENS_MD_DIR = join(REPO_ROOT, "docs", "design", "tokens");
const TOKENS_TS_PATH = join(REPO_ROOT, "app", "frontend", "src", "design", "tokens.ts");
const GLOBALS_CSS_PATH = join(REPO_ROOT, "app", "frontend", "src", "app", "globals.css");

const TOKENS_MARKER_START =
  "/* TOKENS:START — generated by scripts/generate-tokens.ts, do not edit */";
const TOKENS_MARKER_END = "/* TOKENS:END */";

// Canonical role-to-shadcn alias mapping (see research.md §4).
// Each row maps a semantic role name (left, our markdown source) to a shadcn
// alias name (right, what the vendored shadcn primitives reference).
type AliasRow = readonly [semanticRole: string, shadcnAlias: string];
const ROLE_TO_SHADCN_ALIAS: readonly AliasRow[] = [
  ["surface.base", "background"],
  ["content.primary", "foreground"],
  ["surface.base", "card"],
  ["content.primary", "card-foreground"],
  ["surface.base", "popover"],
  ["content.primary", "popover-foreground"],
  ["brand.primary", "primary"],
  ["content.inverted", "primary-foreground"],
  ["surface.muted", "secondary"],
  ["content.primary", "secondary-foreground"],
  ["surface.muted", "muted"],
  ["content.muted", "muted-foreground"],
  ["brand.primary-subtle", "accent"],
  ["content.primary", "accent-foreground"],
  ["status.danger", "destructive"],
  ["content.inverted", "destructive-foreground"],
  ["border.default", "border"],
  ["border.default", "input"],
  ["focus.ring", "ring"],
] as const;

// -----------------------------------------------------------------------------
// Parser — markdown role tables to flat { [path]: rawValue } map
// -----------------------------------------------------------------------------

interface ParsedRow {
  path: string; // dotted, e.g. "surface.base", "text.display"
  value: string; // raw cell text, backticks stripped
  extra?: string; // e.g. line-height for typography rows (column 3)
}

// Strip leading/trailing whitespace AND backticks from a cell.
function cleanCell(cell: string): string {
  return cell.trim().replace(/^`(.*)`$/, "$1").trim();
}

// Parse all role rows from one markdown file.
// A "role row" is a markdown table row whose first cell is a backticked
// dotted path (e.g. `surface.base`, `text.display`, `motion.fast`).
function parseTokenRows(md: string): ParsedRow[] {
  const rows: ParsedRow[] = [];
  const lines = md.split("\n");
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed.startsWith("|") || !trimmed.endsWith("|")) continue;
    const cells = trimmed.slice(1, -1).split("|").map((c) => c.trim());
    if (cells.length < 2) continue;
    const first = cleanCell(cells[0]);
    const originalFirst = cells[0].trim();
    if (!originalFirst.startsWith("`")) continue;
    if (!/^[a-z][a-z0-9]*(\.[a-z0-9-]+)+$/i.test(first)) continue;
    const value = cleanCell(cells[1]);
    const extra = cells.length >= 3 ? cleanCell(cells[2]) : undefined;
    rows.push({ path: first, value, extra });
  }
  return rows;
}

function readAllRows(): ParsedRow[] {
  const files = readdirSync(TOKENS_MD_DIR)
    .filter((f) => f.endsWith(".md") && f !== "README.md")
    .sort();
  const all: ParsedRow[] = [];
  for (const f of files) {
    const md = readFileSync(join(TOKENS_MD_DIR, f), "utf8");
    all.push(...parseTokenRows(md));
  }
  return all;
}

// -----------------------------------------------------------------------------
// Hex to HSL triplet helper
// -----------------------------------------------------------------------------

function hexToHsl(hex: string): string {
  let h = hex.trim();
  if (h.startsWith("#")) h = h.slice(1);
  if (h.length === 3) {
    h = h
      .split("")
      .map((c) => c + c)
      .join("");
  }
  if (h.length !== 6) throw new Error(`hexToHsl: unexpected hex "${hex}"`);
  const r = parseInt(h.slice(0, 2), 16) / 255;
  const g = parseInt(h.slice(2, 4), 16) / 255;
  const b = parseInt(h.slice(4, 6), 16) / 255;
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  let hh = 0;
  let s = 0;
  const l = (max + min) / 2;
  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case r:
        hh = (g - b) / d + (g < b ? 6 : 0);
        break;
      case g:
        hh = (b - r) / d + 2;
        break;
      case b:
        hh = (r - g) / d + 4;
        break;
    }
    hh /= 6;
  }
  const hRound = Math.round(hh * 360);
  const sRound = Math.round(s * 100);
  const lRound = Math.round(l * 100);
  return `${hRound} ${sRound}% ${lRound}%`;
}

function isHex(value: string): boolean {
  return /^#[0-9A-Fa-f]{3}$|^#[0-9A-Fa-f]{6}$/.test(value);
}

// -----------------------------------------------------------------------------
// Bucket assignment — first segment of path → bucket name
// -----------------------------------------------------------------------------

const COLOR_PREFIXES = new Set([
  "surface",
  "border",
  "content",
  "brand",
  "status",
  "focus",
  "overlay",
]);

interface Buckets {
  colors: Record<string, unknown>;
  space: Record<string, string>;
  fontSize: Record<string, [string, { lineHeight: string }] | string>;
  fontFamily: Record<string, string>;
  borderRadius: Record<string, string>;
  transitionDuration: Record<string, string>;
}

function emptyBuckets(): Buckets {
  return {
    colors: {},
    space: {},
    fontSize: {},
    fontFamily: {},
    borderRadius: {},
    transitionDuration: {},
  };
}

function setNested(
  obj: Record<string, unknown>,
  pathSegments: string[],
  value: unknown,
): void {
  let cursor = obj;
  for (let i = 0; i < pathSegments.length - 1; i += 1) {
    const seg = pathSegments[i];
    if (!(seg in cursor) || typeof cursor[seg] !== "object" || cursor[seg] === null) {
      cursor[seg] = {};
    }
    cursor = cursor[seg] as Record<string, unknown>;
  }
  cursor[pathSegments[pathSegments.length - 1]] = value;
}

function pxValue(raw: string): string {
  const m = /^(\d+(?:\.\d+)?)\s*px$/.exec(raw.trim());
  if (m) return `${m[1]}px`;
  return raw.trim();
}

function msValue(raw: string): string {
  const m = /^(\d+(?:\.\d+)?)\s*ms$/.exec(raw.trim());
  if (m) return `${m[1]}ms`;
  return raw.trim();
}

function buildBuckets(rows: ParsedRow[]): Buckets {
  const buckets = emptyBuckets();
  for (const row of rows) {
    const segs = row.path.split(".");
    const head = segs[0];
    if (COLOR_PREFIXES.has(head)) {
      setNested(buckets.colors as Record<string, unknown>, segs, row.value);
    } else if (head === "space") {
      const key = segs.slice(1).join(".");
      buckets.space[key] = pxValue(row.value);
    } else if (head === "radius") {
      const key = segs.slice(1).join(".");
      buckets.borderRadius[key] = pxValue(row.value);
    } else if (head === "text") {
      const key = segs.slice(1).join(".");
      const size = pxValue(row.value);
      const lh = row.extra ? pxValue(row.extra) : "";
      buckets.fontSize[key] = lh ? [size, { lineHeight: lh }] : size;
    } else if (head === "motion") {
      const key = segs.slice(1).join(".");
      buckets.transitionDuration[key] = msValue(row.value);
    }
    // Other prefixes (font.*, ease.*) are skipped: tailwind.config bucket
    // list is colors, fontSize, fontFamily, borderRadius, transitionDuration.
    // fontFamily stays empty (no per-token font-family row in typography.md).
  }
  return buckets;
}

// -----------------------------------------------------------------------------
// tokens.ts emission
// -----------------------------------------------------------------------------

function serializeJsLike(value: unknown, indent: string): string {
  if (typeof value === "string") return JSON.stringify(value);
  if (Array.isArray(value)) {
    const items = value.map((v) => serializeJsLike(v, indent + "  "));
    return `[${items.join(", ")}]`;
  }
  if (typeof value === "object" && value !== null) {
    const entries = Object.entries(value as Record<string, unknown>);
    if (entries.length === 0) return "{}";
    const parts = entries.map(([k, v]) => {
      const keyStr = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(k) ? k : JSON.stringify(k);
      return `${indent}  ${keyStr}: ${serializeJsLike(v, indent + "  ")}`;
    });
    return `{\n${parts.join(",\n")},\n${indent}}`;
  }
  return JSON.stringify(value);
}

function buildTokensTs(buckets: Buckets): string {
  const header =
    "// AUTO-GENERATED by app/frontend/scripts/generate-tokens.ts — do not edit by hand.\n";
  const body = serializeJsLike(buckets, "");
  return `${header}export const tokens = ${body} as const;\nexport type Tokens = typeof tokens;\n`;
}

// -----------------------------------------------------------------------------
// CSS-vars block emission (semantic-role layer + shadcn-alias layer)
// -----------------------------------------------------------------------------

function* walkColors(
  obj: Record<string, unknown>,
  prefix: string[] = [],
): Generator<[string, string]> {
  for (const [k, v] of Object.entries(obj)) {
    const path = [...prefix, k];
    if (typeof v === "string") {
      yield [path.join("."), v];
    } else if (typeof v === "object" && v !== null) {
      yield* walkColors(v as Record<string, unknown>, path);
    }
  }
}

function roleToVar(role: string): string {
  return `--${role.replace(/\./g, "-")}`;
}

function buildCssBlock(rows: ParsedRow[], buckets: Buckets): string {
  const lines: string[] = [];
  lines.push(":root {");

  for (const row of rows) {
    const head = row.path.split(".")[0];
    if (!COLOR_PREFIXES.has(head)) continue;
    const v = row.value;
    let cssValue: string;
    if (isHex(v)) {
      cssValue = hexToHsl(v);
    } else {
      cssValue = v;
    }
    lines.push(`  ${roleToVar(row.path)}: ${cssValue};`);
  }

  lines.push("");
  lines.push("  /* shadcn aliases */");
  for (const [role, alias] of ROLE_TO_SHADCN_ALIAS) {
    let exists = false;
    for (const [path] of walkColors(buckets.colors as Record<string, unknown>)) {
      if (path === role) {
        exists = true;
        break;
      }
    }
    if (!exists) {
      throw new Error(
        `generate-tokens: alias "${alias}" references missing role "${role}". ` +
          `Add it to docs/design/tokens/colors.md or remove the alias mapping.`,
      );
    }
    lines.push(`  --${alias}: var(${roleToVar(role)});`);
  }

  const radiusMd = buckets.borderRadius["md"];
  if (typeof radiusMd === "string") {
    lines.push(`  --radius: ${radiusMd};`);
  }

  lines.push("}");
  return lines.join("\n");
}

// -----------------------------------------------------------------------------
// File assembly + dry-run diff
// -----------------------------------------------------------------------------

function assembleGlobalsCss(currentCss: string, generatedBlock: string): string {
  const startIdx = currentCss.indexOf(TOKENS_MARKER_START);
  const endIdx = currentCss.indexOf(TOKENS_MARKER_END);
  if (startIdx === -1 || endIdx === -1) {
    throw new Error(
      `generate-tokens: missing TOKENS markers in ${GLOBALS_CSS_PATH}. ` +
        `Expected "${TOKENS_MARKER_START}" and "${TOKENS_MARKER_END}".`,
    );
  }
  const before = currentCss.slice(0, startIdx);
  const after = currentCss.slice(endIdx + TOKENS_MARKER_END.length);
  return `${before}${TOKENS_MARKER_START}\n${generatedBlock}\n${TOKENS_MARKER_END}${after}`;
}

function unifiedDiffHead(
  expected: string,
  actual: string,
  label: string,
  maxLines = 40,
): string {
  const e = expected.split("\n");
  const a = actual.split("\n");
  const out: string[] = [`--- ${label} (committed)`, `+++ ${label} (regenerated)`];
  const len = Math.max(e.length, a.length);
  for (let i = 0; i < len && out.length < maxLines + 2; i += 1) {
    const eLine = e[i] ?? "";
    const aLine = a[i] ?? "";
    if (eLine === aLine) continue;
    out.push(`-${eLine}`);
    out.push(`+${aLine}`);
  }
  return out.slice(0, maxLines + 2).join("\n");
}

export interface GeneratedArtefacts {
  tokensTs: string;
  globalsCss: string;
  buckets: Buckets;
}

export function generate(): GeneratedArtefacts {
  const rows = readAllRows();
  const buckets = buildBuckets(rows);
  const tokensTs = buildTokensTs(buckets);
  const cssBlock = buildCssBlock(rows, buckets);
  const currentCss = readFileSync(GLOBALS_CSS_PATH, "utf8");
  const globalsCss = assembleGlobalsCss(currentCss, cssBlock);
  return { tokensTs, globalsCss, buckets };
}

export function buildTokensTsFromDisk(): string {
  return generate().tokensTs;
}

export function buildGlobalsCssFromDisk(): string {
  return generate().globalsCss;
}

// -----------------------------------------------------------------------------
// CLI
// -----------------------------------------------------------------------------

function readFileMaybe(p: string): string {
  try {
    return readFileSync(p, "utf8");
  } catch {
    return "";
  }
}

function main(): void {
  const argv = process.argv.slice(2);
  const checkMode = argv.includes("--check");
  const { tokensTs, globalsCss } = generate();

  const committedTokensTs = readFileMaybe(TOKENS_TS_PATH);
  const committedGlobalsCss = readFileMaybe(GLOBALS_CSS_PATH);

  if (checkMode) {
    let drift = false;
    if (committedTokensTs !== tokensTs) {
      drift = true;
      process.stderr.write(
        unifiedDiffHead(committedTokensTs, tokensTs, "src/design/tokens.ts") + "\n",
      );
    }
    if (committedGlobalsCss !== globalsCss) {
      drift = true;
      process.stderr.write(
        unifiedDiffHead(committedGlobalsCss, globalsCss, "src/app/globals.css") + "\n",
      );
    }
    if (drift) {
      process.stderr.write("tokens-drift: regeneration would change committed files.\n");
      process.exit(1);
    }
    process.exit(0);
  }

  writeFileSync(TOKENS_TS_PATH, tokensTs, "utf8");
  writeFileSync(GLOBALS_CSS_PATH, globalsCss, "utf8");
  process.stdout.write("tokens: regenerated tokens.ts and globals.css\n");
}

const isDirectInvocation = process.argv[1] && resolve(process.argv[1]) === resolve(SCRIPT_FILE);
if (isDirectInvocation) {
  main();
}
