"""Regenerate the committed OpenAPI contract.

    uv run python -m app.backend.generate_openapi            # write
    uv run python -m app.backend.generate_openapi --check    # detect drift

The committed contract at ``app/backend/openapi.yaml`` is byte-deterministic:
``sort_keys=True`` ordering + UTF-8 block style. A pytest companion
(``test_openapi_regeneration``) enforces drift detection on every test run;
this CLI is the equivalent one-shot tool for tight edit loops and CI jobs
that want an explicit check step without spinning up pytest.
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

import yaml

from app.backend.main import app

OPENAPI_PATH: Path = Path(__file__).resolve().parent / "openapi.yaml"


def build_yaml_bytes() -> bytes:
    """Serialise the live OpenAPI dict to deterministic YAML bytes."""
    schema = app.openapi()
    text = yaml.safe_dump(
        schema,
        sort_keys=True,
        allow_unicode=True,
        default_flow_style=False,
    )
    return text.encode("utf-8")


def write_yaml(path: Path) -> None:
    path.write_bytes(build_yaml_bytes())


def check_yaml(path: Path) -> int:
    regenerated = build_yaml_bytes()
    try:
        committed = path.read_bytes()
    except FileNotFoundError:
        sys.stderr.write(
            f"openapi drift: {path} is missing — run "
            "`uv run python -m app.backend.generate_openapi` to create it.\n"
        )
        return 1
    if committed == regenerated:
        return 0
    diff_lines = difflib.unified_diff(
        committed.decode("utf-8").splitlines(),
        regenerated.decode("utf-8").splitlines(),
        fromfile=f"{path} (committed)",
        tofile=f"{path} (regenerated)",
        lineterm="",
    )
    sys.stderr.write("openapi drift detected:\n")
    for line in list(diff_lines)[:40]:
        sys.stderr.write(line + "\n")
    return 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the committed file disagrees with the regenerated bytes.",
    )
    args = parser.parse_args(argv)
    if args.check:
        return check_yaml(OPENAPI_PATH)
    write_yaml(OPENAPI_PATH)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
