// AUTO-GENERATED by app/frontend/scripts/generate-tokens.ts — do not edit by hand.
export const tokens = {
  colors: {
    surface: {
      base: "#FFFFFF",
      raised: "#FAFAFA",
      muted: "#F4F4F5",
      sunken: "#EEEEF0",
      inverted: "#1A1A1A",
    },
    border: {
      subtle: "#ECECEE",
      default: "#E3E3E6",
      strong: "#CFCFD3",
    },
    content: {
      primary: "#111111",
      secondary: "#4B4B52",
      muted: "#8A8A93",
      subtle: "#B4B4BB",
      inverted: "#FFFFFF",
    },
    brand: {
      primary: "#E8573C",
      "primary-hover": "#D04A30",
      "primary-active": "#B53D25",
      "primary-subtle": "#FDECE6",
      link: "#E8573C",
      "link-hover": "#C94026",
    },
    status: {
      info: "#2B6FB4",
      "info-subtle": "#EAF2FB",
      success: "#1E8554",
      "success-subtle": "#E6F4EC",
      warning: "#9A6B00",
      "warning-subtle": "#FBF1DC",
      danger: "#B42318",
      "danger-subtle": "#FBEAE8",
      neutral: "#6C6C75",
      "neutral-subtle": "#F0F0F2",
    },
    focus: {
      ring: "#E8573C",
    },
    overlay: {
      scrim: "rgba(17, 17, 17, 0.45)",
    },
  },
  space: {
    "0": "0px",
    "1": "4px",
    "2": "8px",
    "3": "12px",
    "4": "16px",
    "5": "20px",
    "6": "24px",
    "8": "32px",
    "10": "40px",
    "12": "48px",
    "16": "64px",
  },
  fontSize: {
    display: ["32px", {
        lineHeight: "40px",
      }],
    headline: ["24px", {
        lineHeight: "32px",
      }],
    title: ["20px", {
        lineHeight: "28px",
      }],
    subtitle: ["18px", {
        lineHeight: "26px",
      }],
    body: ["16px", {
        lineHeight: "24px",
      }],
    "body-dense": ["14px", {
        lineHeight: "20px",
      }],
    caption: ["13px", {
        lineHeight: "18px",
      }],
    small: ["12px", {
        lineHeight: "16px",
      }],
  },
  fontFamily: {},
  borderRadius: {
    none: "0px",
    xs: "2px",
    sm: "4px",
    md: "6px",
    lg: "10px",
    xl: "14px",
    pill: "9999px",
  },
  transitionDuration: {
    instant: "0ms",
    fast: "100ms",
    base: "150ms",
    medium: "200ms",
    slow: "300ms",
  },
} as const;
export type Tokens = typeof tokens;
